services: 
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file :
      - .env
    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file :
      - .env
    healthcheck:
      test: ["CMD", "/usr/local/bin/health.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ~/data/db
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ~/data/wp
      o: bind

networks:
  inception:
    name: inception
